version: '3'
services:
  my-express:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-express-container
    ports:
      - "3001:3000"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
